test:
  # adapter: mysql2
  adapter: sqlite3
  database: test_vim_game
  user: root
  password:
  host: localhost
  encoding: utf8

development:
  # adapter: mysql2
  adapter: sqlite3
  database: development_vim_game
  user: root
  password:
  host: localhost
  encoding: utf8
 
production:
  # adapter: mysql2
  adapter: sqlite3
  database: vim_game
  user: root
  password:
  host: localhost
  encoding: utf8

