source 'http://rubygems.org'

gem 'rails', '3.0.10'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

group :development, :test do
	# gem 'evergreen', :require => 'evergreen/rails'
	gem "jasmine"
	gem 'jasmine-headless-webkit'
	gem 'guard-jasmine-headless-webkit'
  gem 'capybara' 
  gem 'database_cleaner' 
  gem 'cucumber-rails' 
  gem 'cucumber' 
  gem 'spork' 
  gem 'rspec-rails'
  gem 'launchy'
  gem 'capybara'
	gem 'therubyracer'
  
  #PREREQUISITE (DEBIAN): sudo apt-get install xvfb
  gem 'headless'
  #PREREQUISITE (DEBIAN): sudo apt-get install libqt4-dev
  gem 'capybara-webkit' #, :git => "git://github.com/thoughtbot/capybara-webkit"
end  


group :development do
  gem "mongrel", "1.2.0.pre2"
  gem "cgi_multipart_eof_fix"
  gem "fastthread"
  gem "railroady"
end

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
  gem 'syntax'
  gem "ci_reporter", ">1.6.5"
  gem 'simplecov', :require => false
  gem 'simplecov-rcov', :require => false  
end

platforms :ruby_18 do
  gem 'ruby-debug', :require => 'ruby-debug'
end  
platforms :ruby_19 do
  gem 'ruby-debug19', :require => 'ruby-debug'
end

